### ISSUE TITLE
List issues improvement

### ISSUE THREAD

**Issue by emreyanik** [Muhit-co/api#1]
- [ ] If the issue is supported by the person who make request, there should be a variable for that **(isSupported)**
- [ ] If request end of the data, there should be a variable for that **(isEndOfList)**

**Comment by gcg** [comment]
@EmreYanik89 ilk istediğin is_supported 1,0 ile tamamdır abi deneyebilirsin. 2. istediğin için ise data boş geldiğinde bittiğini anlama şansın var ise süper olur. Feed yapısı uzadıkça end of datayı bilmeme durumum artabilir. Eğer empty de bittiğini anlarsan benim için süper olur ben de web için aynı mantıkla ilerliyorum
